# Return all athlete stats (age, height, weight).
# This can be compared by {{sex}} and {{sport}}. Filters chosen by user on interface.
# NOTE COMMENTS IN QUERY.

PREFIX wso: <http://wallscope.co.uk/ontology/olympics/>
PREFIX wSport: <http://wallscope.co.uk/resource/olympics/sport/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT (AVG(?fWeight) AS ?avgFWeight) (AVG(?mWeight) AS ?avgMWeight) (AVG(?fHeight) AS ?avgFHeight) (AVG(?mHeight) AS ?avgMHeight) (AVG(?fAge) AS ?avgFAge) (AVG(?mAge) AS ?avgMAge)
# Stats are split by sex on return. By default, these should be combined (mean) until a sex is chosen in the dropdown.
WHERE {
  ?cis wso:continentInSportAverageMaleWeight ?mWeight ;
       wso:continentInSportAverageMaleHeight ?mHeight ;
       wso:continentInSportAverageMaleAge ?mAge ;
       wso:continentInSportAverageFemaleWeight ?fWeight ;
       wso:continentInSportAverageFemaleHeight ?fHeight ;
       wso:continentInSportAverageFemaleAge ?fAge ;
       wso:hasSport wSport:Swimming . # This should be a variable by default! When user selects "Swimming" in dropdown, variable is set to wSport:Swimming.
}