PREFIX walls: <http://wallscope.co.uk/ontology/olympics/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX noc: <http://wallscope.co.uk/resource/olympics/NOC/>
PREFIX res: <http://wallscope.co.uk/resource/>
PREFIX ath: <http://wallscope.co.uk/resource/olympics/athlete>

select ?athlete ?medal ?event ?games ?city
where {
    ?instance walls:games ?games ;
              walls:athlete ?athlete ;
              walls:medal ?medal ;
              walls:event ?event .
    ?games    dbp:location ?city .
}
limit 100